# Python CircleCI 2.1 configuration file
version: 2.1

# Aliases to reuse
_defaults: &defaults
  docker:
    - image: cimg/python:3.11.8
    # - image: cimg/python:3.12
  working_directory: ~/project


jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout

      - run:
          name: Run tests
          command: |
            pip install --upgrade setuptools pip
            pip install -r requirements.txt
            pip install carbontracker pytest
            pip install coverage coveralls pytest-xdist
            # coverage run -m pytest --ignore-glob="*/excl_test_*,*/*excl.py,*/pkgs*"
            git clone git@github.com:eustomaqua/PyFairness.git
            cp -r ./PyFairness/pyfair ./
            coverage run -m pytest test_fair_int.py
            coverage report
            coverage html
            # rm *.png && rm *.csv && rm *.log
            rm -r pyfair exp1b*.pdf
            coverage xml
            export CODACY_PROJECT_TOKEN=f9e9619d28d24ab78f9f39e25a7650c7
            export CODECOV_TOKEN=076f3576-adf2-431b-a02a-9b2a6dc32d82
            export COVERALLS_REPO_TOKEN=ZiMX3Qa3hMaTJZOJHhUmrOxwH3wSmdiRw
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
            # bash <(curl -Ls https://coverage.codacy.com/get.sh)
            # python -m pytest fairml/facils/excl_test*
            # rm chart*.pdf && rm cheers*.pdf && rm fairgbm*.pdf

      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  version: 2
  default:
    jobs:
      - build-and-test
